/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rmjoanwldqckapzmpacr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtam9hbndsZHFja2Fwem1wYWNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY2NjQzMTEsImV4cCI6MjEwMjI0MDMxMX0.k3kN_l_tgBjgCeb11H3TcN-7TLt5-qRbrL6XlOHftcY"